import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth, signOut } from "@/auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session?.user ?
        (<><h1>{session?.user?.email}</h1>
        <form action={async ()=>
          {
            "use server"
            await signOut();
          }}>
          <button type="submit">Log out</button>
        </form>
          </>
        )
        :
        (<h1>Not logged in</h1>)}
        {children}
      </body>
    </html>
  );
}
